// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var a = "\xe8\xbf\x99\xe6\x98\xaf\xe4\xb8\x80\xe6\xae\xb5\xe4\xb8\xad\xe6\x96\x87";

function fn(t) {
  return "" + t + "现在通过函数返回";
}

function fn_u(t) {
  return "" + t + "现在通过Uncurried函数返回";
}

var r1 = fn(a);

var r1_1 = fn(a);

var r2 = fn_u(a);

var r3 = "" + "\xe8\xbf\x99\xe9\x87\x8c\xe4\xb9\x9f\xe6\x98\xaf\xe4\xb8\x80\xe4\xba\x9b\xe6\x96\x87\xe5\xad\x97" + "现在通过函数返回";

console.log(r1);

console.log(r1_1);

console.log(r2);

exports.a = a;
exports.fn = fn;
exports.fn_u = fn_u;
exports.r1 = r1;
exports.r1_1 = r1_1;
exports.r2 = r2;
exports.r3 = r3;
/* r1 Not a pure module */
